### PR TITLE
One page - Compress engine code option to save 500KB (LZ4)

### PR DESCRIPTION
**Pull request by yaustar**
Added option that should only be used if the extra space is needed as it adds extra loading time at the start for decompressing.

Decompression times: ~180ms on Google Pixel 2XL and on Samsung S7

Flappy Bird example:
[Flappy Bird Compressed Engine.html.zip](https://github.com/playcanvas/playcanvas-rest-api-tools/files/6534737/Flappy.Bird.Compressed.Engine.html.zip)

Much, much faster than using fflate in this PR https://github.com/playcanvas/playcanvas-rest-api-tools/pull/16 at the cost of 200KB size difference.

Downside is the browser compatibility as it uses the `require` function to include the library.  Edit: I think lz4.js polyfills this. 🤔

### CODE REVIEW

**Comment by yaustar** [comment]
I've tried the compression on the game data but that only saved 45KB so decided not to include it

**Comment by yaustar** [comment]
Just tested this against Facebook Ads, doesn't work due to the way it imports the lz4.js library :(

**Comment by yaustar** [comment]
Possible other libraries to use: 
https://github.com/kripken/lzma.js
https://github.com/ukyo/lz4.js
Fork of https://github.com/Benzinga/lz4js

**Comment by yaustar** [comment]
Re-tested on Facebook. Turns out I forgot to set the other settings needed for FB and the LZ4 library loading actually does work as a FB Playable Ad 👍

**Review by willeastcott — APPROVED** [review]

**Comment by Maksims** [comment]
Perhaps it should compress based on file extensions because some files compress really well, and some don't.
For example text-based files: txt, glsl, css, html, js, json - they will compress well.
But: png, jpeg - will not.

So it will be good to evaluate which files compress well and provide a config array of extensions to compress.

**Comment by yaustar** [comment]
Hmm, the game scripts, config.json and scene.json could be good candidates.

In my tests, I was doing it after the the base64 conversion which is probably not great for compression. Doing it as part of the asset load patch would be a possibility 🤔

**Comment by Maksims** [comment]
Definitely, I've noticed that base64 is not well compressing too. So doing compression before base64 will be beneficial.

**Pull request merged**
