### PR TITLE
One page - Compress engine code option to save 700KB

### PR DESCRIPTION
**Pull request by yaustar**
Added option that should only be used if the extra space is needed as it adds extra loading time at the start for decompressing.

~600ms on Google Pixel 2XL and ~1800ms on Samsung S7

out

### CODE REVIEW

**Comment by willeastcott** [comment]
This looks cool although the decompress time is a lot for an ad! I wonder whether we can also get good mileage from making it easier to build custom engine versions and drop things like the physics engine, the particle system, various resource handlers and so on.

**Comment by willeastcott** [comment]
Is this a technique used by other playable ad engines?

**Comment by yaustar** [comment]
I don't think it is used for other JS engines, not sure about engines like Defold etc as I would have thought they use WASM.

Maybe we could compress the data or have an option of compressing the data instead which would be smaller in size?

**Comment by yaustar** [comment]
If we do go down the engine pruning root, this compression method can also be used and could potentially be quicker as there is less to decompress.

**Comment by yaustar** [comment]
Closing in favour of https://github.com/playcanvas/playcanvas-rest-api-tools/pull/18 which is much faster on devices (180ms on both the Google Pixel 2 XL and Samsung S7).

**Pull request closed without merging**
